name: Learning

on: [push]

env:
  ARTIFACT_NAME: myartifact

jobs:
  job1:
    name: Challenge
    runs-on: ubuntu-22.04 
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Upload Artifact
        uses: actions/upload-artifact@v3
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: .
